### ISSUE TITLE
Access Denied 

### ISSUE THREAD

**Issue by cubantonystark** [cubantonystark/map_maker_1_2#25]
Access denied while accessing the folder to upload the zip file to the cloud

C:\map_maker_1_2\ARTAK_MM/POST/Lidar/exyn_Morning_Dew_Alpha_NJ2NYC-V1/Data/Model
Sending the file =C:\map_maker_1_2\ARTAK_MM/POST/Lidar/exyn_Morning_Dew_Alpha_NJ2NYC-V1/Data/Model
Exception in thread t6:
Traceback (most recent call last):
  File "C:\Users\escam\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\escam\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\map_maker_1_2\MM_GUI.py", line 608, in main_processing_loop
    MM_upload_to_artak_mk1.upload(each_project.zip_payload_location)
  File "C:\map_maker_1_2\MM_upload_to_artak_mk1.py", line 52, in upload
    file_zip = open(the_file, "rb")
PermissionError: [Errno 13] Permission denied: 'C:\\map_maker_1_2\\ARTAK_MM/POST/Lidar/exyn_Morning_Dew_Alpha_NJ2NYC-V1/Data/Model'

**Comment by cubantonystark** [comment]
solved in Pull Request #26
